### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Camiao64** [Cesare0328/RVS#1]
Task manager displays roblox as 32 bit after using it and does not work on this game
https://www.roblox.com/games/13559584718/Lone-Survival-OPEN-TEST
they have anti uwp and if you try to join a game server inside it ur game will just freeze

**Comment by Cesare0328** [comment]
this is fixed for version [1.3](https://github.com/Cesare0328/RVS/releases/tag/1.3) now

**Comment by Camiao64** [comment]
![image](https://github.com/Cesare0328/RVS/assets/121247685/b25a2e37-070a-4c49-bc33-58ba82e653ba)
uh still having same issues

**Comment by Cesare0328** [comment]
My program does not alter the bit architecture of the application as it is built that way. Instead, it spoofs certain parts of the application to prevent game developers from detecting you for using the 32-bit architecture version of Roblox.

**Comment by Camiao64** [comment]
> My program does not alter the bit architecture of the application as it is built that way. Instead, it spoofs certain parts of the application to prevent game developers from detecting you for using the 32-bit architecture version of Roblox.


i see thanks but any idea why it it doesnt work for this game though?
https://www.roblox.com/games/13559584718/Lone-Survival-OPEN-TEST
