### ISSUE TITLE
works on arsenal but not on counterblox can you fix?

### ISSUE THREAD

**Issue by MisterPenis** [Cesare0328/RVS#4]
^^^^^^

**Comment by HackedApp** [comment]
counterblox is the same as arensals uwp block. must be a problem on your side

**Comment by MisterPenis** [comment]
> counterblox is the same as arensals uwp block. must be a problem on your side

it just freezes up and doesnt load

**Comment by Cesare0328** [comment]
> ^^^^^^

This is bypassed on version [1.4](https://github.com/Cesare0328/RVS/releases/tag/1.4) now
