### ISSUE TITLE
executors crashed now...

### ISSUE THREAD

**Issue by ajiajijiajiaj** [Cesare0328/RVS#6]
yeah so apparently the freeze on loading screen is work no but  i cant attached any exeutors including oxygen u

**Comment by HackedApp** [comment]
they got patched silly

**Comment by ajiajijiajiaj** [comment]
> they got patched silly

what patched? the issue or the program?

**Comment by HackedApp** [comment]
the executors

**Comment by ajiajijiajiaj** [comment]
> the executors

no bro its not patched until i launched the program it works very well even on my other device

**Comment by ajiajijiajiaj** [comment]
I'm completly sorry for misunderstands here the program perfectly fine just me forgot to downgrade it sorry for the inconvenience
